const cosplays = [
    {
      id: 1,
      personagem: "Monkey D. Luffy",
      anime: "One Piece",
      cosplayer: "Renata C.",
      evento: "Anime Friends 2024",
      data: "2024-07-21",
      custo: 550.00,
      avaliacao: 9.5,
      fotos: ["luffy-cosplay-1.jpg", "luffy-cosplay-2.jpg"],
    },
    {
      id: 2,
      personagem: "Levi Ackerman",
      anime: "Attack on Titan",
      cosplayer: "João V.",
      evento: "Comic Con Experience 2023",
      data: "2023-12-03",
      custo: 800.00,
      avaliacao: 9.8,
      fotos: ["levi-cosplay-1.jpg", "levi-cosplay-2.jpg"],
    },
    {
      id: 3,
      personagem: "Sailor Moon",
      anime: "Sailor Moon",
      cosplayer: "Beatriz A.",
      evento: "Geek City 2022",
      data: "2022-09-10",
      custo: 420.00,
      avaliacao: 9.0,
      fotos: ["sailor-moon-cosplay-1.jpg", "sailor-moon-cosplay-2.jpg"],
    },
    {
      id: 4,
      personagem: "Goku Super Saiyajin",
      anime: "Dragon Ball Z",
      cosplayer: "Felipe L.",
      evento: "Ressaca Friends 2024",
      data: "2024-01-28",
      custo: 650.00,
      avaliacao: 9.2,
      fotos: ["goku-cosplay-1.jpg", "goku-cosplay-2.jpg"],
    },
    {
      id: 5,
      personagem: "Sakura Kinomoto",
      anime: "Cardcaptor Sakura",
      cosplayer: "Camila S.",
      evento: "Anime Summit 2023",
      data: "2023-08-15",
      custo: 380.00,
      avaliacao: 8.7,
      fotos: ["sakura-cosplay-1.jpg", "sakura-cosplay-2.jpg"],
    },
    {
      id: 6,
      personagem: "Naruto Uzumaki",
      anime: "Naruto Shippuden",
      cosplayer: "Guilherme R.",
      evento: "BGS 2023",
      data: "2023-10-14",
      custo: 500.00,
      avaliacao: 9.4,
      fotos: ["naruto-cosplay-1.jpg", "naruto-cosplay-2.jpg"],
    },
    {
      id: 7,
      personagem: "Kenshin Himura",
      anime: "Samurai X",
      cosplayer: "Lucas P.",
      evento: "Anime Friends 2023",
      data: "2023-07-23",
      custo: 720.00,
      avaliacao: 9.6,
      fotos: ["kenshin-cosplay-1.jpg", "kenshin-cosplay-2.jpg"],
    },
    {
      id: 8,
      personagem: "Eren Yeager",
      anime: "Attack on Titan",
      cosplayer: "André M.",
      evento: "Geek City 2023",
      data: "2023-09-09",
      custo: 780.00,
      avaliacao: 9.7,
      fotos: ["eren-cosplay-1.jpg", "eren-cosplay-2.jpg"],
    },
    {
      id: 9,
      personagem: "Jujutsu Kaisen",
      anime: "Gojo Satoru",
      cosplayer: "Thiago O.",
      evento: "Anime XP 2024",
      data: "2024-04-05",
      custo: 900.00,
      avaliacao: 9.9,
      fotos: ["gojo-cosplay-1.jpg", "gojo-cosplay-2.jpg"],
    },
    {
      id: 10,
      personagem: "Inosuke Hashibira",
      anime: "Demon Slayer",
      cosplayer: "Rodrigo T.",
      evento: "Anime Friends 2024",
      data: "2024-07-22",
      custo: 680.00,
      avaliacao: 9.3,
      fotos: ["inosuke-cosplay-1.jpg", "inosuke-cosplay-2.jpg"],
    },
  ];
  
  export default { cosplays };