const cosplays = [
    {
      id: 1,
      personagem: "Monkey D. Luffy",
      anime: "One Piece",
      cosplayer: "Renata C.",
      evento: "Anime Friends 2024",
      data: "2024-07-21",
      custo: 550.00,
      avaliacao: 10,
      fotos: ["https://i.imgur.com/gK9qQ4D.jpg", "https://i.imgur.com/k6lP09r.jpg"],
    },
    {
      id: 2,
      personagem: "Levi Ackerman",
      anime: "Attack on Titan",
      cosplayer: "João V.",
      evento: "Comic Con Experience 2023",
      data: "2023-12-03",
      custo: 800.00,
      avaliacao: 8,
      fotos: ["https://i.imgur.com/5lF8xS5.jpg", "https://i.imgur.com/4bB9L2c.jpg"],
    },
    {
      id: 3,
      personagem: "Sailor Moon",
      anime: "Sailor Moon",
      cosplayer: "Beatriz A.",
      evento: "Geek City 2022",
      data: "2022-09-10",
      custo: 420.00,
      avaliacao: 9,
      fotos: ["https://i.imgur.com/s6Ea1yP.jpg", "https://i.imgur.com/w1iYJ6c.jpg"],
    },
    {
      id: 4,
      personagem: "Goku Super Saiyajin",
      anime: "Dragon Ball Z",
      cosplayer: "Felipe L.",
      evento: "Ressaca Friends 2024",
      data: "2024-01-28",
      custo: 650.00,
      avaliacao: 9,
      fotos: ["https://i.imgur.com/1B9qR4X.jpg", "https://i.imgur.com/2X8gP7C.jpg"],
    },
    {
      id: 5,
      personagem: "Sakura Kinomoto",
      anime: "Cardcaptor Sakura",
      cosplayer: "Camila S.",
      evento: "Anime Summit 2023",
      data: "2023-08-15",
      custo: 380.00,
      avaliacao: 7,
      fotos: ["https://i.imgur.com/H1tN7Q9.jpg", "https://i.imgur.com/w0D7r8E.jpg"],
    },
    {
      id: 6,
      personagem: "Naruto Uzumaki",
      anime: "Naruto Shippuden",
      cosplayer: "Guilherme R.",
      evento: "BGS 2023",
      data: "2023-10-14",
      custo: 500.00,
      avaliacao: 8,
      fotos: ["https://i.imgur.com/j4YpT2h.jpg", "https://i.imgur.com/7gM9J8v.jpg"],
    },
    {
      id: 7,
      personagem: "Kenshin Himura",
      anime: "Samurai X",
      cosplayer: "Lucas P.",
      evento: "Anime Friends 2023",
      data: "2023-07-23",
      custo: 720.00,
      avaliacao: 10,
      fotos: ["https://i.imgur.com/uQW9p3E.jpg", "https://i.imgur.com/E5L6b8B.jpg"],
    },
    {
      id: 8,
      personagem: "Eren Yeager",
      anime: "Attack on Titan",
      cosplayer: "André M.",
      evento: "Geek City 2023",
      data: "2023-09-09",
      custo: 780.00,
      avaliacao: 9,
      fotos: ["https://i.imgur.com/K8mXzR1.jpg", "https://i.imgur.com/gO2nQ7v.jpg"],
    },
    {
      id: 9,
      personagem: "Gojo Satoru",
      anime: "Jujutsu Kaisen",
      cosplayer: "Thiago O.",
      evento: "Anime XP 2024",
      data: "2024-04-05",
      custo: 900.00,
      avaliacao: 10,
      fotos: ["https://i.imgur.com/Q9E1P5B.jpg", "https://i.imgur.com/2K4tL8n.jpg"],
    },
    {
      id: 10,
      personagem: "Inosuke Hashibira",
      anime: "Demon Slayer",
      cosplayer: "Rodrigo T.",
      evento: "Anime Friends 2024",
      data: "2024-07-22",
      custo: 680.00,
      avaliacao: 9,
      fotos: ["https://i.imgur.com/z0jV6fC.jpg", "https://i.imgur.com/7G6hX2o.jpg"],
    },
  ];
  
  export default { cosplays };